### ISSUE TITLE
Feature request: include SigDigger's device server

### ISSUE THREAD

**Issue by BatchDrake** [joecupano/SIGpi#24]
Some people use Raspberry Pis to install a headless device server for SigDigger (this is included in Suscan's command line utility, suscli). The most important feature of this server is that it does not forward full rate samples to the net, but only spectrums and decimated channels. This is something that can be useful for low-bandwidth network links.

Since this is still a small program that just depends on Soapy + fftw + libsndfile + libxml, maybe it could be interesting to include it in the default install (and hope this does not sound too much like self-promo!)

**Comment by joecupano** [comment]
All good and a pleasure to meet you. I'll look to includes it in v6.1 which should be in the next two weeks

**Comment by joecupano** [comment]
Did a dry run of the compiles. If SIGpi handles all the dependencies (QT, SigUtils, Suscan, Soapy) do you have deb aarch64 build of SigDigger that could be used?

**Comment by BatchDrake** [comment]
Unfortunately not, but SigDigger is know to work in aarch64. I do have a bunch of automated build scripts if you are interested.

**Comment by joecupano** [comment]
Apologies for missing inclusion in 6.1.   Planning to include in next release

**Comment by joecupano** [comment]
Will be insulded in 6.2 release
