### ISSUE TITLE
Feature Request: Alfa card support

### ISSUE THREAD

**Issue by HarbingerSe7en** [joecupano/SIGpi#27]
Add in support for various Alfa WiFi adapters using Aircrack [drivers](https://github.com/aircrack-ng/rtl8812au)

**Comment by joecupano** [comment]
Is there a specific model you are finding issue with ?   Alfa AWUS036ACM highly recommended

**Comment by HarbingerSe7en** [comment]
AWUS036ACH is the one I use.

**Comment by joecupano** [comment]
Will be in 6.2
