### ISSUE TITLE
Feature Request: aircrack-ng

### ISSUE THREAD

**Issue by HarbingerSe7en** [joecupano/SIGpi#28]
Add software suite for [aircrack-ng](https://github.com/aircrack-ng/aircrack-ng)

**Comment by joecupano** [comment]
Since SIGpi includes Kismet, any diff aircack-ng offfers over the Kismet plugins ?
https://github.com/topics/kismet-plugin

**Comment by HarbingerSe7en** [comment]
I admit I haven't used any of those plugins, but I was under the impression they were deprecated with newer releases of Kismet.

**Comment by joecupano** [comment]
There is rich support for the Kismet ecosystem on their Discord server. Will close for now.

**Comment by HarbingerSe7en** [comment]
I'll add that aircrack-ng does have PW dictionary cracking capabilities.
