### ISSUE TITLE
Feature Request: ZeroTier

### ISSUE THREAD

**Issue by HarbingerSe7en** [joecupano/SIGpi#29]
Add software package for [ZeroTier](https://github.com/zerotier/ZeroTierOne)

SDN (peer-to-peer) for remote access to Pi

**Comment by joecupano** [comment]
So I understand the use case, are you thinking SIGpi Node deployment ?

**Comment by HarbingerSe7en** [comment]
Yeah, remote drop access over an LTE interface using a HAT is something I've done in the past and becomes very easy with ZT. Especially for Kismet applications with servers and drones.

**Comment by joecupano** [comment]
Will plan to include in a 6.X update. Will close when delivered.

**Comment by joecupano** [comment]
Target for 6.3.1

**Comment by joecupano** [comment]
Will be delivered in 6.4
6.3.1 development has become 6.4
