### ISSUE TITLE
SDRPlay RSP1A Not Recognized

### ISSUE THREAD

**Issue by SemperFigh** [joecupano/SIGpi#45]
I have installed SIGpi 6.4 on a fresh Raspberry OS four times now and SDRPlay isn't available as a receiver option. I tested with a RTL_SDR and it works fine. I installed ticking the SDRPlay during install and selected "No" on the autostart dump1090 option. I then tried manually installing API 3.07 from SDRPlay, both before and after installing SIGpi.
I am not a linux ninja, but I can follow instructions on retrieving and providing any info you might need.
Any help/advice/suggestions would be greatly appreciated.

**Comment by SemperFigh** [comment]
As a quick follow up, lsusb shows the device and SoapySDRUtil —list shows the api loaded but SDRPlay doesn’t show up in SDR++ , CubicSDR, or SDRangel.

**Comment by joecupano** [comment]
Thank you for the detail.  Which SDRplay model are you using?

**Comment by SemperFigh** [comment]
Thanx for getting back to me.
I have the RSP1A.
SDRPlay doesn’t show up in the SDR++ drop down menu as an option, nor does it show up as an option in SDRangel. I have SDR++ running on PiSDR and even if the RSP1A isn’t connected the SDRPlay option is in the drop-down… it just doesn’t show anything connected.
If I had to guess I’d say the problem is connected to the SoapySDR SDRPlay module, but I couldn’t find my backside with both hands when it comes to coding.

**Comment by joecupano** [comment]
Please try again with the SIGpi 6.5 release

**Comment by SemperFigh** [comment]
I'm now getting this when running the install script...

./SIGpi_installer.sh: line 92: syntax error in conditional expression
./SIGpi_installer.sh: line 92: syntax error near `22.04*'
./SIGpi_installer.sh: line 92: `if [[ "$SIGPI_OSNAME" = *Ubuntu 22.04* ]]; then'

**Comment by joecupano** [comment]
Cheers ! Will look to have the repo updated this week. Been sick past two weeks.

**Comment by joecupano** [comment]
FYI: While install script for 6.5 fixed, still working on fix for issue RSP1 issue you reported.

**Comment by joecupano** [comment]
Fixed. SDRPlay RSP1 will now work with SDRangel. Replaced SDRPlay drivers and rebuild SDRangel package with support.
