### ISSUE TITLE
Installer OS reconation fault.

### ISSUE THREAD

**Issue by Sjaak066** [joecupano/SIGpi#48]
When trying to install on a ubuntu system I'm getting a fault on line 92 in the installer file (SIGpi_installer.sh)
There ar 2 box brackets to much:

if [ "$SIGPI_OSNAME" = "Debian GNU/Linux 11 (bullseye)" ]; then
    SIGPI_CERTIFIED="true"
fi

if [[ "$SIGPI_OSNAME" = *Ubuntu 22.04* ]]; then
    SIGPI_CERTIFIED="true"
fi

Removed them and the installer works

**Comment by joecupano** [comment]
Cheers ! Will look to have the repo updated this week

**Comment by joecupano** [comment]
Just fixes in main. Thank you
