### ISSUE TITLE
initial run problems

### ISSUE THREAD

**Issue by peterdri** [joecupano/SIGpi#56]
Hello,

When attempting to select options for hardware etc I can select only one option and then enter.
How can I select more than one option?
In one screen the checkboxes were outside the window and could not be accessed, so I could not select even one option.
Now that I want to add more options, please provide the list of TARGETs so I can install manually
Thank you

**Comment by joecupano** [comment]
Are speaking to SIGpi install or a specific SDR application like SDRangel ?

**Comment by peterdri** [comment]
SIGpi install screens with blue background and square bracket selection where I can select a red box with up down arrows

**Comment by peterdri** [comment]
The easiest solution for me is to manually add packages.   Please post the complete list of packages.   I see a list of packages in the SIG/SIGpi/packages folder but I am guessing these are only the packages that were installed, and for example the usrp/uhd package is missing.

I also don't know how to launch a package.   I can start rtl_433 from the command line, but all others I have tried such as gnuradio or grc or dump1090 come up with "command not found".   the GUI Run does not work either   Thanks for your help!

**Comment by joecupano** [comment]
I've tried replicating your issued with a fresh install from the repo but not experiencing it. It sounds like you are not using a fresh Pi distro install. Package info is available on the [wiki](https://github.com/joecupano/SIGpi/wiki).

**Comment by joecupano** [comment]
Closed
